version: '3.4'

services:

  jakartaee-helloworld:
    build: ../backend/Java/EE/Jakarta/10/helloworld
    ports:
    - "8080:8080"
    container_name: jakartaee-helloworld

networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.1/16

